@startuml model

interface Model {
    + predict(input: Tensor) -> Tensor
    + train(input: Tensor, target: Tensor) -> Tensor
    + save(path: String)
    + load(path: String)
}

class MobileNetV3 {

}
note right of MobileNetV3
    [[https://github.com/jerry73204/mobilenet-v3-rs]]
end note

MobileNetV3 -up-|> Model

@enduml